# Generated by Django 5.1.3 on 2025-03-09 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp of when the course was created"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                help_text="Detailed description of the course content"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Status flag indicating if the course is active"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                help_text="The user who created and teaches the course",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses_taught",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(help_text="The title of the course", max_length=255),
        ),
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp of the last update"
            ),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="course",
            field=models.ForeignKey(
                help_text="The course this material belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="file",
            field=models.FileField(
                help_text="The actual file resource", upload_to="course_materials/"
            ),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Status flag indicating if the material is active",
            ),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="title",
            field=models.CharField(
                help_text="The title/name of the material", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp of when the material was uploaded",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of when the course was completed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                help_text="The course the student is enrolled in",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrolled_students",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp of when the enrollment was created",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="is_completed",
            field=models.BooleanField(
                default=False,
                help_text="Status flag indicating if the course is completed",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                help_text="The user enrolled in the course",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrolled_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="comment",
            field=models.TextField(help_text="The feedback content"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="course",
            field=models.ForeignKey(
                help_text="The course the feedback is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks_received",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp of when the feedback was created",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="student",
            field=models.ForeignKey(
                help_text="The user who gave the feedback",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
