# Generated by Django 5.1.3 on 2025-03-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="message_type",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
