# Generated by Django 5.1.3 on 2025-03-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatmessage_file_delete_fileupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
